// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using To_Do.Models;

namespace To_Do.Migrations
{
    [DbContext(typeof(ToDos))]
    [Migration("20211011104247_initial migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("To_Do.Models.ToDoItems", b =>
                {
                    b.Property<int>("todo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("date_added")
                        .HasColumnType("date");

                    b.Property<DateTime>("due_date")
                        .HasColumnType("date");

                    b.Property<string>("task_name")
                        .HasColumnType("varchar(MAX)");

                    b.HasKey("todo_id");

                    b.ToTable("toDoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
